# CI Name
name: PhotobookBE CI

# Run the CI on the following triggers
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# Define the jobs to run on each trigger
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:format
      - run: pnpm test
      - run: pnpm test:e2e
      - run: pnpm build

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://root:password@postgres:5432/test?schema=public&sslmode=prefer
      JWT_SECRET: secret

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
      - run: pnpm install
      - run: pnpm test
